### ISSUE TITLE
MQTT Interface

### ISSUE THREAD

**Issue by Octogonapus** [NickMcSweeney/MQTT.jl#4]
Hi @NickMcSweeney, nice package. It's good to have a Julia MQTT implementation in the ecosystem. I maintain https://github.com/Octogonapus/AWSCRT.jl, which also has an MQTT API. It might be good to try to work out some MQTT interface package which both of our implementations conform to. Not sure that is 100% possible given my package is meant to wrap the AWS CRT as-is, including any oddities it might have, but I figure we could give it a shot. What do you think?

**Comment by NickMcSweeney** [comment]
I like the idea. I was just reading through and basically all the "user" facing functions pretty similar, only Client vs MQTTClient naming, and this has the on_msg callback attached to the client rather than the subscription, plus this doesn't have all the aws stuff in the connection/client. 

If this package had `MQTTClient()`, `connect(client, addr, port)`, `subscribe(client, topic, QOS, callback)`, `publish(client, topic, payload, QOS)`, `unsubscribe(client, topic)` and `disconnect(client)`; would that be enough? they would be pretty interchangeable at that point I think, or were you thinking something more substantial? 

fyi one of my biggest issues with the mqtt implementations for julia has been how the callback was handled, so it is on my list as a thing to change with this package already.

**Comment by Octogonapus** [comment]
I don't think there is a way to abstract how you get a connection. There are too many implementation-dependent details that are needed. These could be passed through the interface via kwargs, but then you just have a leaky interface. I would leave it out. Same goes for creating the client. Do you feel differently? As precedent, [DBInterface.jl does have an empty connect function](https://github.com/JuliaDatabases/DBInterface.jl/blob/85891482dfc5cd2c6c7c40adaf96ad813c9f0a6d/src/DBInterface.jl#LL17-L22), but I think it is pretty useless since you need to look to the implementation to know how to use it.

For the other functions, I think we can get away with:
- `subscribe(callback, connection, topic, qos)` callback first for `do` syntax
- `publish(connection, topic, payload, qos; retain=false)`
- `unsubscribe(connection, topic)`
- `disconnect(connection)`

AWSCRT also has [a top-level on_message](https://octogonapus.github.io/AWSCRT.jl/dev/#AWSCRT.on_message-Tuple{MQTTConnection,%20Union{Nothing,%20Function}}) which I would also put in the interface if this package has it.

We need to define the callback signature: `on_message(topic, payload, dup, qos, retain)`. The arguments `dup`, `qos`, and `retain`, although not typically useful, are returned by the C code, so AWSCRT.jl presents them. Seems like this package doesn't. Would you leave those off?

We need to define the return types of the above functions as well. AWSCRT.jl typically returns a tuple of a task and a packet ID because that is how the C code works. I'm not sure what this package does, or how returning tasks fits in with Dagger.jl.

We need some data types for the connection and QOS:
- `abstract type Connection end`
- `@enum QOS AT_MOST_ONCE=0 AT_LEAST_ONCE=1 EXACTLY_ONCE=2`

Also, this interface should be a separate package `MQTTClientInterface.jl`, ideally under a shared organization. I'm not sure there is one for messaging; I'll ask around.

> fyi one of my biggest issues with the mqtt implementations for julia has been how the callback was handled, so it is on my list as a thing to change with this package already.

What issues were those? I can see how the callbacks in https://github.com/denglerchr/Mosquitto.jl are difficult.

Also you probably should mention https://github.com/rweilbacher/MQTT.jl in the README

**Comment by NickMcSweeney** [comment]
Hey, been busy on some other stuff, but I think I have this in the right direction now.
1. I moved this into a separate project, thought about trying to see if JuliaWeb would take us in, but figured that it would be easier and faster to just put together an MQTT specific project. maybe in the future it turns into JuliaMessaging or something.
2. I made an interface package https://github.com/JuliaMQTT/MQTT.jl with the idea that we can use the [Julia Weak Dependancies](https://pkgdocs.julialang.org/v1/creating-packages/#Weak-dependencies) for doing the interface. I don't think what I have done so far is something that actually runs, but hopefully it is enough to give the right Idea. I added you to both the project and the repo.

**Comment by Octogonapus** [comment]
Thanks! I have also been busy but I took a look this morning at what you have done and I think it looks great. Using package extensions is a good idea. I'll try to work on getting the AWS extension working when I have time.

**Comment by NickMcSweeney** [comment]
I created the project as `JuliaMQTT`, I don't think there is a `JuliaMessaging` project yet, would it be too bold to update the project and see if more than just mqtt stuff wants to go into a shared project location?

**Comment by Octogonapus** [comment]
I think it is fine if you have other projects in mind.
